## Setup

In [1]:
# load code
file = open("./dummy_nn.py")
exec(file.read())
file.close()

In [2]:
# generate data
X_train, y_train = generate_data(2**16)
X_test, y_test = generate_data(2**10)

In [3]:
# note that that a predictor that always predicts that
# a number is not divisible by 3 would have accuracy
1 - sum(y_test)/len(y_test)

0.6484375

## One hidden layer

In [4]:
# generate list of hidden layer sizes to try
sizes = [4*i for i in range(1, n_bits//3+1)]
ls = len(sizes)
hls_list = [tuple([s]) for s in sizes]

In [5]:
# loop over different sizes and print accuracy on test set
for j in hls_list:
    a = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=j, alpha=0.001)
    print(j,a)

(4,) 0.6484375
(8,) 0.6455078125
(12,) 0.6474609375
(16,) 0.6484375
(20,) 0.6484375
(24,) 0.6396484375


## Two hidden layers

In [6]:
# set up 2D matrix to record accuracies of different hls configurations
acc_matrix = np.zeros((ls, ls))

In [7]:
# loop over different hls configurations
for i in range(ls):
    for j in range(ls):
        acc_matrix[i, j] = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(sizes[i], sizes[j]), alpha=0.001)

In [8]:
print(np.array2string(acc_matrix, precision=3))

[[0.72  0.777 0.648 0.766 0.647 0.648]
 [0.651 0.764 0.768 0.647 0.772 0.82 ]
 [0.648 0.646 0.845 0.724 0.648 0.95 ]
 [0.648 0.784 0.837 0.647 0.649 0.647]
 [0.76  0.649 0.69  0.858 0.646 0.756]
 [0.833 0.642 0.828 0.911 0.694 0.791]]


## More hidden layers

In [9]:
# try NNs with more hidden layers
acc_three_hl = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(sizes[2], sizes[1], sizes[0]))
acc_four_hl = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(sizes[3], sizes[2], sizes[1], sizes[0]))

In [10]:
print(acc_three_hl, acc_four_hl)

0.7158203125 0.6376953125


## Decision tree

In [11]:
# try a decision tree
acc_tree = accuracy_tree(X_train, y_train, X_test, y_test)
acc_tree

0.5576171875

## Regularisation parameter

In [12]:
# it seems that two layers work best, where the first layer has the 
# size of the input; now try different rugularisation parameters
alphas = [0.000003, 0.00001, 0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03, 0.1, 0.3]
la = len(alphas)
acc_matrix = np.zeros((ls, la))

In [13]:
for i in range(ls):
    for j in range(la):
        acc_matrix[i, j] = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(n_bits, sizes[i]), alpha=alphas[j])

In [14]:
print(np.array2string(acc_matrix, precision=3))

[[0.803 0.647 0.648 0.648 0.731 0.877 0.737 0.645 0.648 0.64  0.653]
 [0.703 0.654 0.648 0.648 0.648 0.645 0.747 0.709 0.821 0.666 0.874]
 [0.727 0.786 0.702 0.648 0.863 0.767 0.642 0.648 0.645 0.644 0.682]
 [0.834 0.705 0.815 0.871 0.809 0.773 0.647 0.803 0.752 0.729 0.747]
 [0.644 0.642 0.642 0.73  0.817 0.799 0.701 0.867 0.646 0.645 0.642]
 [0.712 0.747 0.645 0.645 0.641 0.869 0.873 0.646 0.873 0.857 0.764]]


(never mind)