## Setup

In [1]:
# load code
file = open("./dummy_nn.py")
exec(file.read())
file.close()

In [2]:
# generate data
X_train, y_train = generate_data(2**14)
X_test, y_test = generate_data(2**10)

In [3]:
# note that that a predictor that always predicts that
# a number is not divisible by 3 would have accuracy
1 - sum(y_test)/len(y_test)

0.68359375

## One hidden layer

In [4]:
# generate list configurations to try as hidden layer sizes
sizes = [4*i for i in range(1, n_bits//3)]
ls = len(sizes)
hls_list = [tuple([s]) for s in sizes]

In [5]:
for j in hls_list:
    a = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=j)
    print(j,a)

(4,) 0.68359375
(8,) 0.6875
(12,) 0.6669921875
(16,) 0.6728515625
(20,) 0.6572265625
(24,) 0.6630859375


## Two hidden layers

In [6]:
acc_matrix = np.zeros((ls, ls))

In [7]:
for i in range(ls):
    for j in range(ls):
        acc_matrix[i, j] = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(sizes[i], sizes[j]))

In [8]:
print(np.array2string(acc_matrix, precision=3))

[[0.763 0.679 0.684 0.778 0.683 0.685]
 [0.686 0.675 0.684 0.661 0.676 0.665]
 [0.667 0.659 0.659 0.674 0.664 0.649]
 [0.684 0.656 0.654 0.65  0.668 0.653]
 [0.682 0.649 0.656 0.66  0.662 0.656]
 [0.651 0.663 0.63  0.618 0.887 0.64 ]]


## Three hidden layers

In [9]:
acc_three_hl = accuracy_hls_config(X_train, y_train, X_test, y_test, hls=(sizes[2], sizes[1], sizes[0]))

In [10]:
acc_three_hl

0.6689453125